Make revision
scidsg/hushline pull request #434
Opened 2024-07-20 02:42 UTC by jeremywmoore

1. Adds a new `revision` target that will initialize a new db migration file.
2. Adds help comments to the `revision` and `migrate` targets so they are listed when running `make help`

2024-07-20 02:44 UTC, jeremywmoore commented
```
% make
fix         Format the code
help        Print the help message
lint        Lint the code
migrate     Apply migrations
revision    Create a new migration
run         Run the app
test        Run the test suite
```

when running without specifying a message name:
```
% make revision
Makefile:31: *** 'message' must be set when invoking the revision target, eg `make revision message="short message"`.  Stop.
```

successful run:
```
% make revision message="short message"
. ./dev_env.sh && \
	poetry run flask db revision -m "short message"
  Generating /Users/jeremymoore/projects/hushline/migrations/versions/82c7cc8d5b80_short_message.py ...  done
```

2024-07-21 00:57 UTC, rmlibre requested changes
Are there places in the docs where this should be added? I see this one:

https://github.com/scidsg/hushline/blob/95c6c5c76ab01212bb30e0220f5d3d11e6a60f1d/docs/DEV.md?plain=1#L51-L57

2024-07-21 00:59 UTC, rmlibre reviewed
#### PS: 

I ran this & the migration commands I used for the last PR [#377], in the current [#411], but both failed to pick up any changes.

Do new tables need to be registered somewhere specific in order to be detected & integrated with the migrations?

2024-07-22 13:46 UTC, jeremywmoore commented on docs/DEV.md
> -Using pipx, install Python packages required for linting and static type checking:
these tools are installed by poetry

2024-07-22 13:47 UTC, jeremywmoore commented
Added the new target to the docs and then cleaned up the targets so users don't have to wrap the calls with `poetry run`.

2024-07-22 13:50 UTC, jeremywmoore commented
> #### PS:
> I ran this & the migration commands I used for the last PR [#377], in the current [#411], but both failed to pick up any changes.
> 
> Do new tables need to be registered somewhere specific in order to be detected & integrated with the migrations?

After creating the new revision file you should populate it with alembic operations to create the table and columns.

2024-07-22 23:05 UTC, rmlibre approved these changes
👍 I like the shortening of the commands

2024-07-23 00:35 UTC, micahflee approved these changes

2024-07-23 00:38 UTC, merged